CREATE TABLE airlines 
(
    ID	VARCHAR(512),
    Short	VARCHAR(512),
    Full	VARCHAR(512)
);

INSERT INTO airlines (ID, Short, Full) VALUES ('001', 'AA', 'American Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('002', '2G', 'CargoItalia (alternate)');
INSERT INTO airlines (ID, Short, Full) VALUES ('005', 'CO', 'Continental Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('006', 'DL', 'Delta Air Lines');
INSERT INTO airlines (ID, Short, Full) VALUES ('012', 'NW', 'Northwest Airlines (alternate site)');
INSERT INTO airlines (ID, Short, Full) VALUES ('014', 'AC', 'Air Canada');
INSERT INTO airlines (ID, Short, Full) VALUES ('016', 'UA', 'United Airlines Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('018', 'CP', 'Canadian Airlines Int´l');
INSERT INTO airlines (ID, Short, Full) VALUES ('020', 'LH', 'Lufthansa Cargo AG');
INSERT INTO airlines (ID, Short, Full) VALUES ('023', 'FX', 'Fedex');
INSERT INTO airlines (ID, Short, Full) VALUES ('027', 'AS', 'Alaska Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('037', 'US', 'USAirways');
INSERT INTO airlines (ID, Short, Full) VALUES ('042', 'RG', 'VARIG Brazilian Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('043', 'KA', 'Dragonair');
INSERT INTO airlines (ID, Short, Full) VALUES ('045', 'LA', 'LAN Chile');
INSERT INTO airlines (ID, Short, Full) VALUES ('047', 'TP', 'TAP Air Portugal');
INSERT INTO airlines (ID, Short, Full) VALUES ('048', 'CY', 'Cyprus Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('050', 'OA', 'Olympic Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('053', 'EI', 'Aer Lingus Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('055', 'AZ', 'Alitalia');
INSERT INTO airlines (ID, Short, Full) VALUES ('057', 'AF', 'Air France');
INSERT INTO airlines (ID, Short, Full) VALUES ('058', 'IC', 'Indian Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('061', 'HM', 'Air Seychelles');
INSERT INTO airlines (ID, Short, Full) VALUES ('064', 'OK', 'Czech Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('065', 'SV', 'Saudi Arabian Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('070', 'RB', 'Syrian Arab Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('071', 'ET', 'Ethiopian Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('072', 'GF', 'Gulf Air');
INSERT INTO airlines (ID, Short, Full) VALUES ('074', 'KL', 'KLM Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('075', 'IB', 'Iberia');
INSERT INTO airlines (ID, Short, Full) VALUES ('076', 'ME', 'Middle East Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('077', 'MS', 'Egyptair');
INSERT INTO airlines (ID, Short, Full) VALUES ('079', 'PR', 'Philippine Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('080', 'LO', 'LOT Polish Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('081', 'QF', 'Qantas Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('082', 'SN', 'Brussels Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('083', 'SA', 'South African Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('086', 'NZ', 'Air New Zealand');
INSERT INTO airlines (ID, Short, Full) VALUES ('090', 'IT', 'Kingfisher Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('093', 'KD', 'KD Avia');
INSERT INTO airlines (ID, Short, Full) VALUES ('096', 'IR', 'Iran Air');
INSERT INTO airlines (ID, Short, Full) VALUES ('098', 'AI', 'Air India');
INSERT INTO airlines (ID, Short, Full) VALUES ('105', 'AY', 'Finnair');
INSERT INTO airlines (ID, Short, Full) VALUES ('106', 'BW', 'Caribbean Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('108', 'FI', 'Icelandair');
INSERT INTO airlines (ID, Short, Full) VALUES ('112', 'CK', 'China Cargo Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('114', 'LY', 'EL AL');
INSERT INTO airlines (ID, Short, Full) VALUES ('115', 'JU', 'JAT Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('117', 'SK', 'SAS-Scandinavian Airlines System');
INSERT INTO airlines (ID, Short, Full) VALUES ('118', 'DT', 'TAAG Angola Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('119', 'LM', 'Air ALM');
INSERT INTO airlines (ID, Short, Full) VALUES ('124', 'AH', 'Air Algerie');
INSERT INTO airlines (ID, Short, Full) VALUES ('125', 'BA', 'British Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('126', 'GA', 'Garuda Indonesia');
INSERT INTO airlines (ID, Short, Full) VALUES ('129', 'MP', 'Martinair Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('131', 'JL', 'Japan Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('133', 'LR', 'LACSA Airlines of Costa Rica');
INSERT INTO airlines (ID, Short, Full) VALUES ('139', 'AM', 'Aeromexico Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('140', 'LI', 'LIAT Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('147', 'AT', 'Royal Air Maroc');
INSERT INTO airlines (ID, Short, Full) VALUES ('148', 'LN', 'Libyan Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('157', 'QR', 'Qatar Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('160', 'CX', 'Cathay Pacific Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('163', '3V', 'TNT Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('165', 'JP', 'Adria Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('172', 'CV', 'Cargolux Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('176', 'EK', 'Emirates');
INSERT INTO airlines (ID, Short, Full) VALUES ('180', 'KE', 'Korean Air');
INSERT INTO airlines (ID, Short, Full) VALUES ('182', 'MA', 'Malev Hungarian Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('183', 'RG', 'VARIG Brazilian Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('189', 'JI', 'Jade Cargo International');
INSERT INTO airlines (ID, Short, Full) VALUES ('201', 'JM', 'Air Jamaica');
INSERT INTO airlines (ID, Short, Full) VALUES ('202', 'TA', 'TACA');
INSERT INTO airlines (ID, Short, Full) VALUES ('205', 'NH', 'ANA All Nippon Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('214', 'PK', 'Pakistan Int´l Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('217', 'TG', 'Thai Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('229', 'KU', 'Kuwait Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('230', 'CM', 'Copa Airlines Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('231', 'NG', 'Lauda Air');
INSERT INTO airlines (ID, Short, Full) VALUES ('232', 'MH', 'Malaysian Airline System');
INSERT INTO airlines (ID, Short, Full) VALUES ('234', 'JD', 'Japan Air System');
INSERT INTO airlines (ID, Short, Full) VALUES ('235', 'TK', 'Turkish Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('236', 'BD', 'British Midland Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('239', 'MK', 'Air Mauritius');
INSERT INTO airlines (ID, Short, Full) VALUES ('257', 'OS', 'Austrian Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('258', 'MD', 'Air Madagascar');
INSERT INTO airlines (ID, Short, Full) VALUES ('265', 'EF', 'Far Eastern Air Transport');
INSERT INTO airlines (ID, Short, Full) VALUES ('266', 'LT', 'LTU (Leisure Cargo)');
INSERT INTO airlines (ID, Short, Full) VALUES ('270', 'TL', 'Trans Mediterranean Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('272', 'K4', 'Kalitta Air');
INSERT INTO airlines (ID, Short, Full) VALUES ('288', 'LD', 'Air Hong Kong');
INSERT INTO airlines (ID, Short, Full) VALUES ('297', 'CI', 'China Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('301', '5S', 'Global Aviation and Services');
INSERT INTO airlines (ID, Short, Full) VALUES ('302', 'OO', 'Sky West Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('307', 'WE', 'Centurion Air Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('324', 'SC', 'Shandong Airlines (Chinese)');
INSERT INTO airlines (ID, Short, Full) VALUES ('330', 'RF', 'Florida West International Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('345', 'NC', 'Northern Air Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('356', 'C8', 'Cargolux Italia');
INSERT INTO airlines (ID, Short, Full) VALUES ('369', '5Y', 'Atlas Air');
INSERT INTO airlines (ID, Short, Full) VALUES ('378', 'KX', 'Cayman Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('390', 'A3', 'Aegean Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('403', 'PO', 'Polar Air Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('404', 'JW', 'Arrow Air');
INSERT INTO airlines (ID, Short, Full) VALUES ('406', '5X', 'UPS Air Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('416', 'N8', 'National Air Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('421', 'S7', 'Siberia Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('423', 'ER', 'DHL Aviation/DHL Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('465', 'KC', 'Air Astana');
INSERT INTO airlines (ID, Short, Full) VALUES ('479', 'ZH', 'Shenzhen Airlines (Chinese)');
INSERT INTO airlines (ID, Short, Full) VALUES ('507', 'SU', 'Aeroflot');
INSERT INTO airlines (ID, Short, Full) VALUES ('512', 'RJ', 'Royal Jordanian');
INSERT INTO airlines (ID, Short, Full) VALUES ('526', 'WN', 'Southwest Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('529', 'A2', 'Cielos Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('549', 'M3', 'ABSA Aerolinhas Brasileiras');
INSERT INTO airlines (ID, Short, Full) VALUES ('552', 'M2', 'Mario’s Air');
INSERT INTO airlines (ID, Short, Full) VALUES ('564', 'XQ', 'Sun Express');
INSERT INTO airlines (ID, Short, Full) VALUES ('566', 'PS', 'Ukraine Int´l Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('572', '9U', 'Air Moldova');
INSERT INTO airlines (ID, Short, Full) VALUES ('575', '7C', 'Coyne Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('580', 'RU', 'AirBridge Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('589', '9W', 'Jet Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('603', 'UL', 'SriLankan Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('603', 'UL', 'more AWB tracking');
INSERT INTO airlines (ID, Short, Full) VALUES ('604', 'UY', 'Cameroon Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('607', 'EY', 'ETIHAD Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('615', 'QY', 'DHL Aviation / European Air Transport');
INSERT INTO airlines (ID, Short, Full) VALUES ('618', 'SQ', 'Singapore Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('623', 'FB', 'Bulgaria Air');
INSERT INTO airlines (ID, Short, Full) VALUES ('631', 'GL', 'Air Greenland');
INSERT INTO airlines (ID, Short, Full) VALUES ('635', 'IY', 'Yemenia Yemen Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('643', 'KM', 'Air Malta');
INSERT INTO airlines (ID, Short, Full) VALUES ('656', 'PX', 'Air Niugini');
INSERT INTO airlines (ID, Short, Full) VALUES ('657', 'BT', 'Air Baltic');
INSERT INTO airlines (ID, Short, Full) VALUES ('672', 'BI', 'Royal Brunei Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('675', 'NX', 'Air Macau');
INSERT INTO airlines (ID, Short, Full) VALUES ('695', 'BR', 'Eva Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('700', '5C', 'CAL Cargo Air Lines');
INSERT INTO airlines (ID, Short, Full) VALUES ('706', 'KQ', 'Kenya Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('716', 'MB', 'MNG Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('724', 'LX', 'Swiss');
INSERT INTO airlines (ID, Short, Full) VALUES ('729', 'QT', 'Tampa Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('731', 'MF', 'Xiamen Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('737', 'SP', 'SATA Air Acores');
INSERT INTO airlines (ID, Short, Full) VALUES ('738', 'VN', 'Vietnam Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('757', 'SM', 'Avient');
INSERT INTO airlines (ID, Short, Full) VALUES ('771', 'J2', 'Azerbaijan Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('774', 'FM', 'Shanghai Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('781', 'MU', 'China Eastern Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('784', 'CZ', 'China Southern Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('800', 'GD', 'Grandstar Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('803', 'AE', 'Mandarin Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('810', 'M6', 'Amerijet International');
INSERT INTO airlines (ID, Short, Full) VALUES ('817', 'S6', 'SAC South American Airways');
INSERT INTO airlines (ID, Short, Full) VALUES ('825', 'F4', 'Shanghai Airlines Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('831', 'OU', 'Croatia Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('851', 'N8', 'Hong Kong Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('858', 'FK', 'Africa West');
INSERT INTO airlines (ID, Short, Full) VALUES ('862', 'EV', 'Atlantic Southeast Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('865', 'MY', 'MASAir');
INSERT INTO airlines (ID, Short, Full) VALUES ('870', 'VV', 'Aerosvit');
INSERT INTO airlines (ID, Short, Full) VALUES ('871', 'Y8', 'Yangtze River Express Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('873', '6R', 'AeroUnion');
INSERT INTO airlines (ID, Short, Full) VALUES ('876', '3U', 'Sichuan Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('880', 'HU', 'Hainan Airlines (Chinese)');
INSERT INTO airlines (ID, Short, Full) VALUES ('881', 'DE', 'Condor Flugdienst');
INSERT INTO airlines (ID, Short, Full) VALUES ('886', 'OH', 'Comair');
INSERT INTO airlines (ID, Short, Full) VALUES ('901', 'B1', 'TAB Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('907', 'QN', 'Air Armenia');
INSERT INTO airlines (ID, Short, Full) VALUES ('928', 'UZ', 'Buraq Air Transport (Arabic only)');
INSERT INTO airlines (ID, Short, Full) VALUES ('932', 'VS', 'Virgin Atlantic');
INSERT INTO airlines (ID, Short, Full) VALUES ('933', 'KZ', 'Nippon Cargo Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('957', 'JJ', 'TAM Brazilian Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('958', '7I', 'Insel Air Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('960', 'OV', 'Estonian Air');
INSERT INTO airlines (ID, Short, Full) VALUES ('976', 'QO', 'Aeromexpress Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('988', 'OZ', 'Asiana Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('989', 'IJ', 'Great Wall Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('996', 'UX', 'Air Europa Cargo');
INSERT INTO airlines (ID, Short, Full) VALUES ('997', 'BG', 'Biman Bangladesh');
INSERT INTO airlines (ID, Short, Full) VALUES ('999', 'CA', 'Air China');
INSERT INTO airlines (ID, Short, Full) VALUES ('610', '2A', 'Air Astra');
INSERT INTO airlines (ID, Short, Full) VALUES ('997', 'BG', 'Biman Bangladesh Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('855', 'VQ', 'Novoair');
INSERT INTO airlines (ID, Short, Full) VALUES ('779', 'BS', 'US-Bangla Airlines');
INSERT INTO airlines (ID, Short, Full) VALUES ('', '', '');
